trigger:
  branches:
    include:
      - main

variables:
  solution: "**/*.sln"
  buildPlatform: "x86"
  buildConfiguration: "Release"

pool:
  vmImage: 'windows-latest'

stages:
  - template: templates/deploy_azure_webapp.yml
    parameters:
      azureSubscription: "My-Service-Connection"
      webAppName: "Sample-Web-App1"
      sourceBranchTrigger: "refs/heads/main"
